#!/usr/bin/env python3
"""Export readable Markdown transcripts from Claude Code session JSONL files.

Claude Code stores one JSONL file per session under
``~/.claude/projects/<encoded-project-path>/``. Each line is a record; the
conversation itself lives in ``user`` and ``assistant`` records. This script
renders the visible conversation (user prompts, assistant prose, thinking
summaries, and a compact log of tool calls) so the chats stay readable even if
a future Claude Code version cannot import the raw files.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

DEFAULT_PROJECT_DIR = (
    Path.home() / ".claude" / "projects" / "-Users-mkfqm-malof-lab"
)

# Synthetic user turns injected by the harness, not typed by the human.
SKIP_USER_MARKERS = (
    "<system-reminder>",
    "<local-command-caveat>",
    "Caveat: The messages below were generated by the user",
)


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--project-dir",
        type=Path,
        default=DEFAULT_PROJECT_DIR,
        help="Claude Code project directory holding the session JSONL files.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("migration_state") / "claude_chat_transcripts",
    )
    parser.add_argument(
        "--include-thinking",
        action="store_true",
        help="Include assistant thinking blocks when they carry visible text.",
    )
    return parser.parse_args()


def block_text(block):
    """Return displayable text for one content block, or None to skip it."""
    kind = block.get("type")
    if kind == "text":
        return block.get("text", "").strip() or None
    if kind == "tool_use":
        name = block.get("name", "tool")
        raw = json.dumps(block.get("input", {}), ensure_ascii=False)
        if len(raw) > 400:
            raw = raw[:400] + " …(truncated)"
        return f"_[tool: {name}]_ `{raw}`"
    if kind == "tool_result":
        return None
    return None


def message_text(message, include_thinking):
    content = message.get("content")
    if isinstance(content, str):
        return content.strip()
    parts = []
    for block in content or []:
        if block.get("type") == "thinking":
            if not include_thinking:
                continue
            thinking = block.get("thinking", "").strip()
            if thinking:
                parts.append(f"> _(thinking)_ {thinking}")
            continue
        text = block_text(block)
        if text:
            parts.append(text)
    return "\n\n".join(parts).strip()


def is_synthetic_user(text):
    stripped = text.lstrip()
    return any(stripped.startswith(marker) for marker in SKIP_USER_MARKERS)


def read_session(path, include_thinking):
    title = None
    started_at = None
    turns = []
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                continue

            kind = record.get("type")
            if kind == "ai-title" and not title:
                title = record.get("aiTitle")
                continue
            if kind == "system" and record.get("subtype") == "compact_boundary":
                turns.append(("compact", "— conversation compacted —"))
                continue
            if kind not in {"user", "assistant"}:
                continue
            if record.get("isMeta"):
                continue

            timestamp = record.get("timestamp")
            if timestamp and not started_at:
                started_at = timestamp

            text = message_text(record.get("message", {}), include_thinking)
            if not text:
                continue
            if kind == "user" and is_synthetic_user(text):
                continue
            turns.append((kind, text))
    return title, started_at, turns


def write_transcript(path, output, include_thinking):
    title, started_at, turns = read_session(path, include_thinking)
    session_id = path.stem
    display_title = title or f"Claude session {session_id[:8]}"
    safe_title = re.sub(r"[^A-Za-z0-9._-]+", "-", display_title).strip("-")[:80]
    destination = output / f"{safe_title}-{session_id}.md"

    lines = [
        f"# {display_title}",
        "",
        "- Source: Claude Code",
        f"- Session ID: `{session_id}`",
        f"- Started: `{started_at or 'unknown'}`",
        f"- Raw source: `{path.name}`",
        "",
    ]
    for role, text in turns:
        if role == "compact":
            lines.extend(("---", "", f"_{text}_", ""))
            continue
        heading = "User" if role == "user" else "Assistant"
        lines.extend((f"## {heading}", "", text, ""))

    destination.write_text("\n".join(lines), encoding="utf-8")
    visible = sum(1 for role, _ in turns if role != "compact")
    return destination, visible


def main():
    args = parse_args()
    if not args.project_dir.exists():
        raise SystemExit(f"Project directory not found: {args.project_dir}")
    args.output.mkdir(parents=True, exist_ok=True)

    sessions = sorted(args.project_dir.glob("*.jsonl"))
    if not sessions:
        raise SystemExit(f"No session JSONL files under {args.project_dir}")

    for path in sessions:
        destination, count = write_transcript(
            path, args.output, args.include_thinking
        )
        print(f"{destination}: {count} visible messages")


if __name__ == "__main__":
    main()
